<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'fakemysqli' => '/../tests/phpTest.php',
                'fakemysqliresult' => '/../tests/phpTest.php',
                'fakestmt' => '/../tests/phpTest.php',
                'phptest' => '/../tests/phpTest.php',
                'zoningfunctionstest' => '/../tests/phpTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
